### ISSUE TITLE
Требуется дополнить описание библиотек.

### ISSUE THREAD

**Issue by MishkinIN** [GeorgGrebenyuk/cs_modelstudio_com_api_about#1]
Прошу дополнить описание библиотек COM API Model Studio CS:

> ironObjCom.idl	 Объекты металлоконструкций	ironObjCom 1.0 Type Library

> mstHVACCOM.idl	Объекты вентиляции	mstHVACCOM 1.0 Type Library

> mstProjectCOM.idl	Объекты проекта (CadLib??)	 mstProjectCOM 1.0 Type Library

> mstRouteCOM.idl	Объекты кабельных конструкций	mstRouteCOM 1.0 Type Library

> ProfileViewCOM.idl	Объекты электросетей (2D)	Model Studio LINE Objects 1.0 Type Library

И спасибо за начинание.

**Comment by GeorgGrebenyuk** [comment]
Спасибо за комментарий, один вопрос -- вентиляция и металлоконструкции это какие ModelStudio? Металл наверное строительные решения, а вот вентиляция - MS Отопление и вентиляция - HEATVENT*

P.S. Нашел
